//! Wiring smoke: KDL config → layout → PanePty → vte → TextGrid
//! → ratatui `TestBackend`. Asserts that text the child emits ends
//! up in both the vte-consumed grid and the rendered ratatui
//! buffer.

use std::time::Duration;

use cmdash::pane::PaneRunner;
use cmdash_layout::{ComputedLayout, Rect as LayoutRect};
use cmdash_pty::{PaneLayerId, ShellSpec};

#[test]
fn wiring_round_trip_renders_echoed_text() {
    let source = r#"layout { pane kind=shell label="wiring" }"#;
    let cfg = cmdash_config::parse(source).expect("parse config");
    let root = cfg.layout.expect("layout block");
    let area = LayoutRect {
        x: 0,
        y: 0,
        w: 80,
        h: 24,
    };
    let layout = ComputedLayout::compute(&root, area).expect("compute layout");
    assert_eq!(layout.panes.len(), 1, "expected 1 leaf pane");
    let pane = layout.panes[0].clone();

    let layer_id = cmdash::derive_layer_id(&pane.id);
    assert_eq!(layer_id, PaneLayerId(pane.id.pre_order() as u64));

    let shell = ShellSpec::Command {
        argv: vec![
            "sh".to_string(),
            "-c".to_string(),
            "printf 'hello world\\n'; sleep 0.05; exit 0".to_string(),
        ],
    };
    let mut runner = PaneRunner::spawn(pane.clone(), layer_id, shell).expect("spawn runner");

    // Allow the child to start. Sleep once up-front lets the
    // reader thread accumulate some bytes; subsequent ticks are
    // bounded by `try_wait` + short sleeps.
    std::thread::sleep(Duration::from_millis(250));

    let mut last_snap = None;
    let mut found_in_grid = false;
    // Tick FIRST so `last_snap` is populated even when the child
    // exits faster than the first iteration's `try_wait_exit` would
    // have returned `Some(_)`.
    for _ in 0..80 {
        let snap = runner.tick().expect("tick");
        if !found_in_grid {
            for y in 0..snap.rows {
                for x in 0..snap.cols {
                    if snap.grid.cell(x, y).ch == 'h' {
                        found_in_grid = true;
                        break;
                    }
                }
                if found_in_grid {
                    break;
                }
            }
        }
        last_snap = Some(snap);
        if found_in_grid {
            break;
        }
        std::thread::sleep(Duration::from_millis(25));
    }
    let snap = last_snap.expect("at least one snapshot");
    assert!(
        found_in_grid,
        "wiring did not surface 'hello' into the grid; rows={} cols={}",
        snap.rows, snap.cols
    );

    // Render to ratatui TestBackend (matches the live `Frame`
    // path: same `blit_grid` helper).
    let backend = ratatui::backend::TestBackend::new(80, 24);
    let mut terminal = ratatui::Terminal::new(backend).expect("terminal");
    terminal
        .draw(|frame| {
            let area = ratatui::layout::Rect::new(0, 0, pane.rect.w, pane.rect.h);
            cmdash::render::blit_grid(&snap.grid, frame.buffer_mut(), area);
        })
        .expect("draw");
    let buf = terminal.backend().buffer().clone();
    let mut saw_h = false;
    for y in 0..24 {
        for x in 0..80 {
            if buf.get(x, y).symbol() == "h" {
                saw_h = true;
                break;
            }
        }
    }
    assert!(saw_h, "rendered buffer did not contain 'h'");
}

// ---------------------------------------------------------------------------
// Kitty graphics end-to-end smoke: push a synthetic image onto
// GraphicsState, render and emit through dashcompositor's
// passthrough encoder, and assert the byte stream contains the
// kitty APC-G escape per AGENTS.md §"Rendering pipeline" step 6.
//
// This covers the dashcompositor routing path without depending
// on a real PTY child or a hand-crafted PNG byte fixture.
// ---------------------------------------------------------------------------

#[test]
fn kitty_graphics_route_emits_escape_sequence() {
    use cmdash::graphics::{GraphicsState, Metrics};
    use cmdash_pty::PaneLayerId;

    let mut graphics = GraphicsState::new(Metrics::default(), (80, 24));
    graphics.push_image(PaneLayerId(1), 7, image::RgbaImage::new(1, 1));

    let mut out = Vec::new();
    graphics
        .render_and_write(&mut out)
        .expect("render_and_write ok");

    assert!(
        out.windows(3).any(|w| w == b"\x1b_G"),
        "encoded stream missing kitty APC-G escape; bytes (first 64): {:?}",
        &out[..out.len().min(64)]
    );
}

// ---------------------------------------------------------------------------
// Regression test for the production `Load → image::load_from_memory`
// path: round-trip a real (committed, verified) PNG byte stream
// through `apply_kitty_event` and confirm the `(pane, kitty_id)` mapping
// is registered. The fixture is regenerated by
// `examples/gen_fixture.rs` if the test ever regresses.
// ---------------------------------------------------------------------------

#[test]
fn kitty_decode_smoke() {
    use cmdash::graphics::{GraphicsState, Metrics};
    use cmdash_pty::{KittyGraphicCmd, PaneLayerId};

    let png = include_bytes!("fixtures/img1x1.png");
    let mut graphics = GraphicsState::new(Metrics::default(), (80, 24));
    let pane = PaneLayerId(1);
    let load = KittyGraphicCmd::Load {
        id: 7,
        placement_id: 0,
        format: 32,
        width: 1,
        height: 1,
        data: png.to_vec(),
    };
    graphics.apply_kitty_event(pane, &load);
    assert!(graphics.has_image(pane, 7));
}

// --------------------------------------------------------------------------
// Regression test pinning the post-resize rect refresh introduced
// when wiring the `PaneRunner::computed` accessor (see
// `PaneRunner::resize` doc in pane.rs). Before the refresh,
// `runner.computed().rect` returned the spawn-time rect forever,
// which broke any caller that read the rect after a terminal
// resize.
//
// Asserts (four post-resize states):
// - the spawn-time rect == pane.rect (initial-state sanity).
// - after `resize(new_w, new_h)`, `runner.computed().rect` ==
//   `LayoutRect{x:0, y:0, w:new_w, h:new_h}`.
// - shrinking is also refreshed (pins not just a one-way
//   growth path).
// - grow-again after shrink -- successive override must not
//   carry any state from the previous call (cache is per-call
//   fresh, not incremental).
// --------------------------------------------------------------------------

#[test]
fn pane_runner_resize_refreshes_computed_rect() {
    let source = r#"layout { pane kind=shell label="resize-regression" }"#;
    let cfg = cmdash_config::parse(source).expect("parse config");
    let root = cfg.layout.expect("layout block");
    let area = LayoutRect {
        x: 0,
        y: 0,
        w: 80,
        h: 24,
    };
    let layout = ComputedLayout::compute(&root, area).expect("compute layout");
    let pane = layout.panes[0].clone();

    let layer_id = cmdash::derive_layer_id(&pane.id);

    // Long-lived but cheap shell so the PTY stays alive across
    // both resize() calls (10s wallclock budget is plenty).
    let shell = ShellSpec::Command {
        argv: vec!["sh".to_string(), "-c".to_string(), "sleep 10".to_string()],
    };
    let mut runner = PaneRunner::spawn(pane.clone(), layer_id, shell).expect("spawn runner");

    // Initial-state sanity: the accessor should hand back the
    // exact spawn-time rect.
    assert_eq!(
        runner.computed().rect,
        LayoutRect {
            x: pane.rect.x,
            y: pane.rect.y,
            w: pane.rect.w,
            h: pane.rect.h,
        },
        "spawn-time rect should match the layout-computed pane.rect"
    );

    // Grow.
    runner
        .resize(LayoutRect {
            x: 0,
            y: 0,
            w: 132,
            h: 50,
        })
        .expect("resize grow");
    assert_eq!(
        runner.computed().rect,
        LayoutRect {
            x: 0,
            y: 0,
            w: 132,
            h: 50
        },
        "post-resize (grow) rect should be (0, 0, 132, 50)"
    );

    // Shrink -- verify refresh works both directions, not just
    // growth.
    runner
        .resize(LayoutRect {
            x: 0,
            y: 0,
            w: 40,
            h: 12,
        })
        .expect("resize shrink");
    assert_eq!(
        runner.computed().rect,
        LayoutRect {
            x: 0,
            y: 0,
            w: 40,
            h: 12
        },
        "post-resize (shrink) rect should be (0, 0, 40, 12)"
    );

    // Grow again -- pins that successive override doesn't carry
    // any state from the previous call. Without this 4th
    // assertion a regression that overwrote via an accumulator
    // (`rect.w += new_w` rather than `rect.w = new_w`) could
    // pass the 3-state test because the cached previous dims
    // are never compared against an unrelated new target.
    runner
        .resize(LayoutRect {
            x: 0,
            y: 0,
            w: 200,
            h: 60,
        })
        .expect("resize grow again");
    assert_eq!(
        runner.computed().rect,
        LayoutRect {
            x: 0,
            y: 0,
            w: 200,
            h: 60
        },
        "post-resize (grow again) rect should be (0, 0, 200, 60)"
    );
}

// ----------------------------------------------------------------------
// Regression test for the v2 split-pane nesting contract lift:
// `PaneRunner::resize(rect)` MUST carry the layout-engine's
// `(x, y)` origin forward into `self.computed.rect` -- not
// zero it out the way v1 did. End-to-end via a real KDL
// `split` config + production `PaneRunner::spawn` path so the
// order `pty.resize()? -> rect overwrite` is pinned through a
// real `PanePty::resize` call against the running PTY (NOT
// just the `StubPty` lib unit-tests cover).
//
// Fixture: parent area (132, 50), `SplitAxis::Horizontal`
// `ratio=0.6` -> child A at `(x:0, w:79, h:50)` and child B at
// `(x:79, w:53, h:50)`. Resize child B from initial
// `(79, 0, 53, 50)` to `(79, 10, 80, 30)` so a v1 regression
// that zeroed either `(x, y)` axis would fail the post-resize
// assert. Sibling-pane orthogonality: A must not mutate when B
// is resized.
// ----------------------------------------------------------------------
#[test]
fn pane_runner_resize_preserves_split_origin_in_layout_engine_path() {
    let source = r#"layout {
        split axis=horizontal ratio=0.6 {
            pane kind=shell label="split-a"
            pane kind=shell label="split-b"
        }
    }"#;
    let cfg = cmdash_config::parse(source).expect("parse split config");
    let root = cfg.layout.expect("layout block");
    let area = LayoutRect {
        x: 0,
        y: 0,
        w: 132,
        h: 50,
    };
    let layout = ComputedLayout::compute(&root, area).expect("compute split layout");
    assert_eq!(layout.panes.len(), 2, "expected 2 leaf panes from split");

    let pane_a = layout.panes[0].clone();
    let pane_b = layout.panes[1].clone();

    // Pre-state pin from `cmdash_layout::split_rect`
    // (`SplitAxis::Horizontal`, `ratio=60` over width 132):
    //   w_left  = 132 * 60 / 100 = 79
    //   child A: (x:0,  y:0, w:79, h:50)
    //   child B: (x:79, y:0, w:53, h:50)
    assert_eq!(
        pane_a.rect,
        LayoutRect {
            x: 0,
            y: 0,
            w: 79,
            h: 50
        },
        "fixture invariant: split child A at (0, 0, 79, 50)"
    );
    assert_eq!(
        pane_b.rect,
        LayoutRect {
            x: 79,
            y: 0,
            w: 53,
            h: 50
        },
        "fixture invariant: split child B at (79, 0, 53, 50)"
    );

    // Long-lived shells -- `sleep 10` keeps both children alive
    // across the resize call so the PTY-side `winresize` flow
    // doesn't error out with `PtyError::InvalidSize` against a
    // short-lived child.
    let shell = ShellSpec::Command {
        argv: vec!["sh".to_string(), "-c".to_string(), "sleep 10".to_string()],
    };
    let id_a = cmdash::derive_layer_id(&pane_a.id);
    let id_b = cmdash::derive_layer_id(&pane_b.id);
    let runner_a = PaneRunner::spawn(pane_a.clone(), id_a, shell.clone()).expect("spawn runner A");
    let mut runner_b =
        PaneRunner::spawn(pane_b.clone(), id_b, shell.clone()).expect("spawn runner B");

    // Initial-state sanity: spawn-time rect rounds-trip the
    // Split-derived non-zero origin (x:79 for child B).
    assert_eq!(runner_b.computed().rect, pane_b.rect);

    // Resize child B with a target rect that exercises ALL
    // four axes: x preserved, y introduced, w + h changed. A
    // v1 regression that zeroed either origin axis would fail
    // the assert below.
    let target = LayoutRect {
        x: 79,
        y: 10,
        w: 80,
        h: 30,
    };
    runner_b
        .resize(target)
        .expect("resize child B with non-zero origin");

    // Post-resize assertion: the FULL rect round-trips.
    assert_eq!(
        runner_b.computed().rect,
        target,
        "split child B post-resize rect must match the caller-supplied full rect"
    );
    // (per-axis asserts removed -- the FULL-rect assert above
    //  catches any deviation across all four axes.)

    // Sibling-pane orthogonality: resize of B MUST NOT mutate
    // A's cached rect.
    assert_eq!(
        runner_a.computed().rect,
        pane_a.rect,
        "sibling pane A's rect must be unaffected by runner B resize"
    );
}

// ----------------------------------------------------------------------
// Phase 2 v2 wiring regression: a `TickContext::relayout(w, h)`
// driven by a host `Event::Resize` must reach a real
// `PaneRunner::resize(rect)` against a running PTY child, NOT
// just a `StubPty` lib test. End-to-end binding exercised:
// crossterm Event::Resize -> handle_event arms
// `pending_resize` -> TickContext::run phase 0.5 take() ->
// `relayout(w, h)` -> `ComputedLayout::compute` -> per-pair
// `runner.resize(pane.rect)` over a real `PanePty`.
//
// Uses `sleep 10` so both panes are still alive when the
// host-driven resize fires (a fast-exit `/bin/true` child
// would race against the assertion surface). The TestBackend
// constructs a ratatui `Terminal` without writing to stdout so
// no real TTY is needed for the test environment.
// ----------------------------------------------------------------------
#[test]
fn relayout_drives_per_pane_resize_via_real_pty() {
    use cmdash_layout::Rect as LayoutRect;

    let source = r#"layout {
        split axis=horizontal ratio=0.6 {
            pane kind=shell label="layout-a"
            pane kind=shell label="layout-b"
        }
    }"#;
    let cfg = cmdash_config::parse(source).expect("parse split config");
    let layout_root = cfg.layout.clone().expect("layout block");

    let (close_tx, _close_rx): (cmdash::pane::PaneCloseTx, _) = std::sync::mpsc::channel();
    let shell_a = ShellSpec::Command {
        argv: vec!["sh".to_string(), "-c".to_string(), "sleep 10".to_string()],
    };
    let shell_b = shell_a.clone();

    // Both panes come from a SHARED ComputedLayout invocation
    // against `layout_root`, so `pane_a_cfg.id` and
    // `pane_b_cfg.id` carry the same `path_len` and pre-order
    // leaf numbering as `post_layout.panes[i].id` (the latter
    // is computed against the same `layout_root` below). This
    // is the load-bearing pairing requirement for
    // `assert_eq!(runner.computed().id, pane.id)` inside the
    // per-pair relayout loop. Earlier draft of this test
    // derived each pane from a separate single-pane KDL string,
    // which yielded `path_len: 1` ids while the split config's
    // leaves have `path_len: 2`, breaking the pre-condition
    // the relayout loop asserts.
    let initial_layout = ComputedLayout::compute(
        &layout_root,
        LayoutRect {
            x: 0,
            y: 0,
            w: 80,
            h: 24,
        },
    )
    .expect("compute initial 80x24 layout from layout_root");
    assert_eq!(
        initial_layout.panes.len(),
        2,
        "expected 2 leaf panes from Split config (one parent + two children)"
    );
    let pane_a_cfg = initial_layout.panes[0].clone();
    let pane_b_cfg = initial_layout.panes[1].clone();

    let id_a = cmdash::derive_layer_id(&pane_a_cfg.id);
    let id_b = cmdash::derive_layer_id(&pane_b_cfg.id);
    let runner_a =
        PaneRunner::spawn_with_graphics(pane_a_cfg.clone(), id_a, shell_a, Some(close_tx.clone()))
            .expect("spawn runner A");
    let runner_b =
        PaneRunner::spawn_with_graphics(pane_b_cfg.clone(), id_b, shell_b, Some(close_tx.clone()))
            .expect("spawn runner B");
    let mut runners = [runner_a, runner_b];
    drop(close_tx);

    // Manual relayout path -- the SAME per-pair loop
    // `TickContext::relayout(132, 50)` runs in the live tick
    // loop, inlined here so this integration test does not
    // reach into the binary crate's main.rs (TickContext
    // lives in `cmdash::src::main.rs`, visible only to the
    // binary's own `#[cfg(test)] mod input_tests`).
    let post_layout = ComputedLayout::compute(
        &layout_root,
        LayoutRect {
            x: 0,
            y: 0,
            w: 132,
            h: 50,
        },
    )
    .expect("compute post-layout 132x50");
    assert_eq!(post_layout.panes.len(), runners.len());
    for (runner, pane) in runners.iter_mut().zip(post_layout.panes.iter()) {
        assert_eq!(
            runner.computed().id,
            pane.id,
            "relayout index pairing: runners[i]/layout.panes[i] PaneId match"
        );
        runner
            .resize(pane.rect)
            .expect("relayout: pane resize must succeed against a sleeping PTY child");
    }

    // Both children are alive (`sleep 10`), so the per-pair
    // `runner.resize(pane.rect)` call must succeed. The
    // cached cell-grid rect must round-trip the
    // `cmdash_layout::split_rect` math over `132 x 50`:
    //   w_left = (132 * 60) / 100 = 79
    //   child A: (x:0,  y:0, w:79, h:50)
    //   child B: (x:79, y:0, w:53, h:50)
    assert_eq!(
        runners[0].computed().rect,
        LayoutRect {
            x: 0,
            y: 0,
            w: 79,
            h: 50
        },
        "child A post-relayout rect must round-trip 132x50 Horizontal-60 split via real PTY"
    );
    assert_eq!(
        runners[1].computed().rect,
        LayoutRect {
            x: 79,
            y: 0,
            w: 53,
            h: 50
        },
        "child B post-relayout rect must round-trip 132x50 Horizontal-60 split via real PTY"
    );

    // Pairing invariant: per-pair `assert_eq!(runner.computed().id,
    // pane.id)` already fired INSIDE the relayout loop above, so a
    // separate post-layout re-derivation is redundant. Leaving the
    // residue of the previously-redundant check as a comment so the
    // intent -- "every relayout asserts the index pairing" -- is
    // visible without re-running ComputedLayout::compute.

    // GraphicsState cells propagation is exercised end-to-end in
    // the matching lib unit test
    // `cmdash::src::main.rs::input_tests::relayout_emits_resize_per_pane_when_host_signals_resize`
    // -- wiring_smoke keeps its surface narrow to the layout ->
    // runner.resize pairing path (GraphiceState is constructed
    // inside `cmdash::main::run` where TickContext owns it).
}
